---
driver:
  name: ec2
  aws_ssh_key_id: bdausses_sa
  region: us-east-2
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Test Kitchen node for BDausses, Chef"
    created-by: "test-kitchen"
    user: chef

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: amazon2-2019
    transport:
      ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[verifier_example::default]
    verifier:
      inspec_tests:
        - name: inspec-profile-wrapper-example
          url: https://github.com/bdausses/inspec-profile-wrapper-example
    attributes:
